### ISSUE TITLE
Cannot run on ubuntu

### ISSUE THREAD

**Issue by ajunge** [ConsenSys/btcrelay-fetchd#1]
With python (v2.7):

```
$ python fetchd.py -s 0x467d3b01ca6c94a9a6053c437c9e5310a63589a5 -r 0x2fd4f3ae10608cd6192339e72d4f6a0c182dee22 -n btc --rpcPort 8545 --fetch -d --gasPrice 500000000000
Traceback (most recent call last):
  File "fetchd.py", line 9, in <module>
    from pyepm import api, config, __version__
  File "/usr/local/lib/python2.7/dist-packages/pyepm/api.py", line 17, in <module>
    from serpent import get_prefix, decode_datalist
ImportError: cannot import name get_prefix
```

With python3

```
$ python3 fetchd.py -s 0x467d3b01ca6c94a9a6053c437c9e5310a63589a5 -r 0x2fd4f3ae10608cd6192339e72d4f6a0c182dee22 -n btc --rpcPort 8545 --fetch -d --gasPrice 500000000000
Traceback (most recent call last):
  File "fetchd.py", line 9, in <module>
    from pyepm import api, config, __version__
  File "/usr/local/lib/python3.4/dist-packages/pyepm/api.py", line 13, in <module>
    from colors import colors
ImportError: No module named 'colors'


```

**Comment by kobigurk** [comment]
Works with python 2.7. I think the backport of the modules didn't go so well (colors, StringIO).

**Comment by ethers** [comment]
@ajunge I also updated the readme in November: https://github.com/ConsenSys/btcrelay-fetchd#recommended
(Haven't tried on Python3)

**Comment by ethers** [comment]
Closing this since there have been several updates since this was filed.  Python 2.7 should work

**Comment by jerinamathews** [comment]
It wont work in python 2.7. Most of the other dependencies are compatible only with python 3. like eth-hash
